### ISSUE TITLE
SystemError: unknown opcode

### ISSUE THREAD

**Issue by hans-thomas** [kanjvt/Skillshare-DL#1]
Hi, when i run `dl.py`  i keep getting the below error.
```bash
python3 dl.py https://www.skillshare.com/classes/A-Splash-Of-Embroidery-Anyone-Can-Embroider/1532912352/projects
XXX lineno: -1, opcode: 42
Traceback (most recent call last):
  File "/opt/projects/github/Skillshare-DL/dl.py", line 2, in <module>
    from skillshare import Skillshare, splash
  File "/opt/projects/github/Skillshare-DL/skillshare.py", line 4, in <module>
    from abrakadabra import kanjut
  File "</opt/projects/github/Skillshare-DL/abrakadabra.py>", line 3, in <module>
  File "<frozen abrakadabra>", line -1, in <module>
SystemError: unknown opcode

```
thanks

**Comment by scriptcuddle** [comment]
im using python 3.9 and this is working fine

what's your python version?

![skillshare-downloader](https://telegra.ph/file/8fec72dc69990e0a8d037.png)
